"use client";
import Link from "next/link";
import { ArrowRight, ShoppingBag, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { readLocal, clearCart, type CartItem } from "@/lib/traveler";
import { Photo } from "@/components/Photo";
import { usePhase, FeatureGate } from "@/components/PhaseProvider";
export default function CartPage() {
  const { has } = usePhase();
  const [item,setItem] = useState<CartItem|null>(null); const [loaded,setLoaded] = useState(false);
  useEffect(() => {const saved=readLocal<CartItem|null>("tb-cart-experience",null);setItem(saved ? {...saved,journey:has("connectedJourney")?saved.journey:undefined}:null);setLoaded(true);},[]);
  function change(travelers:number) { if (!item) return; const next = {...item,travelers};setItem(next);window.localStorage.setItem("tb-cart-experience",JSON.stringify(next));window.localStorage.setItem("tb-last-travelers",String(travelers)); }
  const subtotal = item ? item.price * item.travelers + (item.journey?.recommendation?.price || 0) * item.travelers + (item.journey?.transfers.reduce((sum,leg) => sum + leg.option.price,0) || 0) + (item.journey?.guidePrice || 0) : 0;
  return <div className="workspace-page"><div className="content-width"><div className="page-heading"><div><h1>A good day, in the making.</h1><p>Review your experience before continuing.</p></div><span className="demo-badge">Demo checkout · No real charge</span></div>{!loaded ? <p role="status">Opening your cart…</p> : item ? <div className="cart-layout"><div className="checkout-card"><div className="summary-item"><Photo src={item.image} alt={item.title} /><div><strong>{item.title}</strong><span>{item.selectedOption}</span><span>{item.selectedDate} · {item.selectedTime}</span></div></div><div className="cart-item-controls"><div className="field"><label htmlFor="cart-travelers">Travelers</label><select id="cart-travelers" value={item.travelers} onChange={(e) => change(Number(e.target.value))}>{[1,2,3,4,5,6].map((value) => <option key={value} value={value}>{value} {value === 1 ? "person" : "people"}</option>)}</select></div><Link className="text-link" href={`/experience/${item.id}`}>Change booking options</Link><button className="text-link" onClick={() => {if(window.confirm("Remove this experience from your local cart?")){clearCart();setItem(null);}}}><Trash2 size={15} /> Remove</button></div>{item.journey && <div className="inline-note">Connected journey: {item.journey.transfers.length} demo transfers{item.journey.recommendation && ` · ${item.journey.recommendation.title}`}. Transport is simulated.</div>}<p className="inline-note">{item.freeCancellation ? "Sample cancellation policy: free cancellation up to 24 hours before departure." : "This sample option is non-refundable."}</p></div><aside className="checkout-card"><h2>Your booking estimate</h2><div className="cost-row"><span>Experience & options</span><strong>${subtotal.toFixed(2)}</strong></div><div className="cost-row"><span>Service fee (8%)</span><strong>${(Math.round(subtotal*.08*100)/100).toFixed(2)}</strong></div><div className="cost-row total"><span>Estimated total</span><strong>${(subtotal + Math.round(subtotal*.08*100)/100).toFixed(2)}</strong></div><Link href="/checkout" className="button button-primary button-wide" style={{marginTop:22}}>Continue to checkout <ArrowRight size={16} /></Link><p className="inline-note">This prototype creates a local demo booking. No payment is taken.</p></aside></div> : <div className="empty-state"><ShoppingBag size={34} /><h2>Your next experience is out there.</h2><p>Choose an experience and its options to start a demo booking.</p><Link href="/search" className="button button-primary">Explore experiences <ArrowRight size={16} /></Link></div>}</div></div>;
}
