"use client";
import Link from "next/link";
import { Eye, Plus, FileText } from "lucide-react";
import { useEffect, useState } from "react";
import { experiences } from "@/lib/catalog";
import { readLocal } from "@/lib/traveler";
import { PortalLayout, supplierNav } from "@/components/Portal";
import { Photo } from "@/components/Photo";
export default function SupplierProductsPage(){const [draft,setDraft] = useState<{title:string;destination:string}|null>(null);useEffect(() => setDraft(readLocal("tb-supplier-draft",null)),[]);return <PortalLayout role="Supplier center" title="Your experiences" subtitle="Browse the sample catalog or shape a new local draft." nav={supplierNav}><div className="form-navigation" style={{margin:"0 0 25px"}}><span className="inline-note" style={{margin:0}}>{experiences.length} sample listings</span><Link className="button button-primary" href="/supplier/products/new"><Plus size={16} /> Create experience</Link></div>{draft && <div className="notice" style={{marginBottom:25}}><FileText size={18} /><div><strong>{draft.title || "Untitled draft"}</strong><br />{draft.destination || "Destination to be added"} · Saved on this device</div><Link className="text-link" href="/supplier/products/new" style={{marginLeft:"auto"}}>Continue editing</Link></div>}<div className="portal-card listing-table"><div className="table-head" style={{gridTemplateColumns:"2fr 110px 100px"}}><span>Experience</span><span>Sample price</span><span>Preview</span></div>{experiences.map((experience) => <div className="table-row" style={{gridTemplateColumns:"2fr 110px 100px"}} key={experience.id}><div style={{display:"flex",flexDirection:"row",gap:14,alignItems:"center"}}><Photo src={experience.image} alt="" className="listing-thumb" /><span><strong>{experience.title}</strong><small>{experience.destination} · Sample listing</small></span></div><strong>${experience.price}</strong><Link className="text-link" aria-label={`Preview ${experience.title}`} href={`/experience/${experience.id}`}><Eye size={17} /> View</Link></div>)}</div></PortalLayout>;}
