import Link from "next/link";
import { ArrowRight, Check, MapPinned, ShieldCheck, Sparkles } from "lucide-react";
import { destinations, categories, experiences } from "@/lib/catalog";
import { ExperienceCard } from "@/components/ExperienceCard";
import { SearchBar } from "@/components/AppShell";

export default function HomePage() {
  return <>
    <section className="hero"><div className="hero-inner"><div className="hero-copy"><div className="eyebrow">Make room for wonder</div><h1>Find the feeling<br />you’re looking for.</h1><p>Curated experiences, local stories and unforgettable moments — wherever you’re headed next.</p><div className="hero-search"><SearchBar /></div><Link className="hero-live-link" href="/search"><span><MapPinned size={17} /> Looking for something happening now?</span><strong>Explore things to do nearby <ArrowRight size={14} /></strong></Link></div></div></section>
    <section className="section"><div className="section-inner"><div className="section-heading"><div><div className="eyebrow">The world is waiting</div><h2>Popular destinations</h2></div><Link className="section-link" href="/destinations">See all destinations <ArrowRight size={14} /></Link></div><div className="destination-grid">{destinations.map((destination) => <Link href={`/search?q=${destination.name}`} className="destination-card" key={destination.name}><img src={destination.image} alt={destination.name} /><div className="destination-info"><h3>{destination.name}</h3><span>{destination.count} experiences · {destination.country}</span></div></Link>)}</div></div></section>
    <section className="section section-muted"><div className="section-inner"><div className="section-heading"><div><div className="eyebrow">Made for your kind of curious</div><h2>Experiences worth travelling for</h2><p>Handpicked by our team, loved by travelers, and ready for your next chapter.</p></div><Link className="section-link" href="/search">Explore all <ArrowRight size={14} /></Link></div><div className="experience-grid">{experiences.slice(0, 4).map((experience) => <ExperienceCard key={experience.id} experience={experience} />)}</div></div></section>
    <section className="section"><div className="section-inner"><div className="section-heading"><div><div className="eyebrow">Choose your mood</div><h2>Explore by category</h2></div></div><div className="category-pills">{categories.map((category) => <Link className="category-pill" href={`/search?category=${encodeURIComponent(category)}`} key={category}>{category}</Link>)}</div></div></section>
    <section className="section section-muted"><div className="section-inner"><div className="promo-band"><div><div className="eyebrow">Travel Buddy Rewards</div><h2>Good trips come back around.</h2><p>Earn credit on every eligible booking and put it towards the next adventure.</p><Link className="button button-primary" href="/account" style={{ marginTop: 20 }}>Join for free <ArrowRight size={16} /></Link></div><div className="promo-icon"><Sparkles size={40} /></div></div></div></section>
    <section className="section"><div className="section-inner trust-section"><div><div className="eyebrow">Go with confidence</div><h2>More than a booking.<br />A better way to travel.</h2><p className="muted">We take care of the small details so you can stay present for the big moments.</p><div className="trust-list"><div className="trust-item"><span className="trust-icon"><Check size={17} /></span><div><strong>Real local expertise</strong><p>Every experience is hosted by people who know and love their place.</p></div></div><div className="trust-item"><span className="trust-icon"><ShieldCheck size={17} /></span><div><strong>Flexible when plans change</strong><p>Book with peace of mind and cancel select experiences for free.</p></div></div></div></div><div className="review-quote"><div className="rating-stars">★★★★★ <span style={{ color: "var(--muted)", fontWeight: 400 }}>4.9 average</span></div><blockquote>“The kind of evening that makes you fall a little bit in love with a city.”</blockquote><div className="review-author"><span className="avatar">JC</span><span><strong>Jamie Chen</strong><br /><span className="muted">Colombo, Sri Lanka</span></span></div></div></div></section>
  </>;
}
