"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { CalendarDays, Compass, Heart, MapPinned, Search, ShoppingBag, UserRound, ArrowUpRight } from "lucide-react";
import { useEffect, useId, useState } from "react";
import { readLocal } from "@/lib/traveler";
export function Brand() { return <Link href="/" className="brand" aria-label="TravelBuddy home"><span className="brand-mark"><Compass size={23} strokeWidth={1.8} /></span><span>travel<span>buddy</span><i>.</i></span></Link>; }
export function AppShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname(); const [cartCount, setCartCount] = useState(0);
  useEffect(() => { document.documentElement.dataset.theme = readLocal<string>("tb-theme", "light"); }, []);
  useEffect(() => { const update = () => setCartCount(Number(window.localStorage.getItem("tb-cart-count") || 0)); update(); window.addEventListener("tb-cart-updated", update); return () => window.removeEventListener("tb-cart-updated", update); }, []);
  const portal = ["/supplier", "/advisor", "/partner", "/admin"].some((route) => pathname === route || pathname.startsWith(`${route}/`));
  const focused = pathname === "/checkout" || pathname.startsWith("/login") || pathname === "/register";
  const active = (href: string) => href === "/" ? pathname === "/" || ["/search", "/destinations", "/experience", "/inspiration"].some((route) => pathname.startsWith(route)) : href === "/trips" ? pathname.startsWith("/trips") || pathname === "/wishlist" || pathname === "/scan" || pathname.startsWith("/booking") : pathname.startsWith(href);
  const navigation = [{ label: "Explore", href: "/", icon: Compass }, { label: "Trips", href: "/trips", icon: CalendarDays }, { label: "Guides", href: "/guide", icon: MapPinned }, { label: "Profile", href: "/account", icon: UserRound }];
  return <div className={`app-shell ${portal ? "portal-app-shell" : ""} ${focused ? "focused-shell" : ""}`}><a href="#main-content" className="skip-link">Skip to content</a>{!portal && <header className="site-header"><Brand />{!focused && <nav className="desktop-nav" aria-label="Traveler navigation">{navigation.slice(0, 3).map((item) => <Link key={item.href} href={item.href} className={active(item.href) ? "active" : ""} aria-current={active(item.href) ? "page" : undefined}>{item.label === "Trips" ? "My Trips" : item.label === "Guides" ? "Local Guides" : item.label}</Link>)}</nav>}<div className="header-actions">{focused ? <Link className="text-link" href="/trips">Back to my trips</Link> : <><Link href="/saved" className="header-icon" aria-label="Saved experiences"><Heart size={20} /></Link><Link href="/cart" className="header-icon cart-button" aria-label={`Cart${cartCount ? `, ${cartCount} item` : ""}`}><ShoppingBag size={20} />{cartCount > 0 && <b>{cartCount}</b>}</Link><Link href="/account" className={`account-button ${active("/account") ? "active" : ""}`}><UserRound size={18} /><span>Profile</span></Link></>}</div></header>}<main id="main-content">{children}</main>{!portal && !focused && <><nav className="mobile-bottom-nav" aria-label="Traveler navigation">{navigation.map(({ icon: Icon, ...item }) => <Link key={item.href} href={item.href} className={active(item.href) ? "active" : ""} aria-current={active(item.href) ? "page" : undefined}><span><Icon size={22} /></span>{item.label}</Link>)}</nav><footer className="site-footer"><div className="footer-main"><div><Brand /><p>A little curiosity.<br />A whole world to discover.</p></div><div><h4>Go explore</h4><Link href="/search">All experiences</Link><Link href="/destinations">Destinations</Link><Link href="/guide">Local guides</Link></div><div><h4>Make it yours</h4><Link href="/trips">My trips</Link><Link href="/saved">Saved experiences</Link><Link href="/support">Help & support</Link></div><div><h4>TravelBuddy for business</h4><Link href="/login">Explore demo workspaces <ArrowUpRight size={14} /></Link><p className="footer-demo">Prototype experience.<br />Sample listings. No real charges.</p></div></div><div className="footer-bottom"><span>© 2026 TravelBuddy</span><span>English · Prices in USD</span><Link href="/support">About this prototype</Link></div></footer></>}</div>;
}
export function SearchBar({ compact = false }: { compact?: boolean }) { const id = useId(); return <form className={`search-bar ${compact ? "compact" : ""}`} action="/search"><div className="search-field"><MapPinned size={22} /><div><label htmlFor={`${id}-q`}>Where would you like to go?</label><input id={`${id}-q`} name="q" placeholder="Destination or experience" autoComplete="off" /></div></div><div className="search-field date-field"><CalendarDays size={21} /><div><label htmlFor={`${id}-date`}>When?</label><input id={`${id}-date`} name="date" type="date" /></div></div><button type="submit" className="button button-primary search-submit"><Search size={19} /><span>Explore</span></button></form>; }
