"use client";
import Link from "next/link";
import { ArrowLeft, ArrowRight, Check, MapPin, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { readBookings, type Booking } from "@/lib/traveler";
import { experiences } from "@/lib/catalog";
import { Photo } from "./Photo";
import { getDemo } from '@/lib/demo';
import { usePhase, FeatureGate } from "./PhaseProvider";
export function BookingDetails({id,confirmation = false}:{id:string;confirmation?:boolean}) {
  const { has } = usePhase();const bookingsHref=has("tripPlanner")?"/trips?view=bookings":"/bookings";const [booking,setBooking] = useState<Booking|null>(null);const [loaded,setLoaded] = useState(false);useEffect(() => {setBooking(readBookings().find((item) => item.id === id) || null);setLoaded(true);},[id]);
  if (!loaded) return <div className="empty-state" role="status">Opening booking…</div>;
  if (!booking) return <div className="empty-state"><h1>This booking isn’t on this device.</h1><p>Demo booking records stay in the browser where they were created.</p><Link href={bookingsHref} className="button button-primary">My bookings</Link></div>;
  if (confirmation) return <div className="confirmation-page"><div className="confirmation-symbol"><Check size={29} /></div><h1>A good day is on the way.</h1><p>Your demo booking has been saved. You can find the experience, meeting point, and booking reference in your booking history.</p><span className="demo-badge">Demo confirmation · No real booking or charge</span><div className="checkout-card"><div className="summary-item"><Photo src={booking.image} alt="" /><div><strong>{booking.title}</strong><span>{booking.date} · {booking.travelers} travelers</span><span>Reference: {booking.id}</span></div></div><Link className="button button-primary button-wide" style={{marginTop:25}} href={`/booking/${booking.id}`}>View booking details <ArrowRight size={16} /></Link></div><Link className="text-link" href={bookingsHref}>View my bookings <ArrowRight size={16} /></Link></div>;
  return <div className="ticket-page"><div className="ticket-inner"><Link href={bookingsHref} className="back-link"><ArrowLeft size={16} /> My bookings</Link><div className="ticket-heading"><h1>Your day, ready to discover.</h1><span className="demo-badge">Demo booking</span></div><article className="ticket-card"><Photo src={booking.image} alt={booking.title} className="ticket-cover" /><div className="ticket-body"><span className="status">{getDemo().bookings.find(b=>b.id===booking.id)?.status ? "Demo " + getDemo().bookings.find(b=>b.id===booking.id)!.status.toLowerCase() : booking.payLater ? "Demo reserved · Payment pending" : "Demo confirmed"}</span><h2>{booking.title}</h2><dl className="ticket-facts"><div><dt>Date</dt><dd>{booking.date}</dd></div><div><dt>Start time</dt><dd>{booking.time}</dd></div><div><dt>Travelers</dt><dd>{booking.travelers}</dd></div><div><dt>Total estimate</dt><dd>${booking.total.toFixed(2)} USD</dd></div><div><dt>Payment</dt><dd>{booking.payLater ? "Simulated pay later" : "Simulated · No charge"}</dd></div></dl><div className="ticket-reference">Booking reference: <strong>{booking.id}</strong></div><h3>Meet here</h3><p><MapPin size={16} style={{verticalAlign:"-3px"}} /> {booking.meetingPoint}</p><a className="text-link" href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(booking.meetingPoint)}`} target="_blank" rel="noreferrer">Open location in maps <ArrowRight size={14} /></a>{booking.experienceIds.length > 1 && <><h3>Your experience sequence</h3>{booking.experienceIds.map((experienceId) => { const experience = experiences.find((item) => item.id === experienceId);return experience ? <p key={experienceId}><Link className="text-link" href={`/experience/${experienceId}`}>{experience.title}</Link><br />{experience.meetingPoint}</p> : null; })}</>}<div className="notice"><ShieldCheck size={18} /><span>This is a local prototype record, not a valid admission ticket. No supplier has received this booking. Your reference is for this demo only.</span></div></div></article><Link className="button button-secondary" style={{marginTop:25}} href="/support">Help with this demo</Link></div></div>;
}
