"use client";
import { useState } from "react";
import { MapPin } from "lucide-react";
import { guideProfiles, experiences } from "@/lib/catalog";
import { GuideProfileCard } from "./GuideProfileCard";
import { Photo } from "./Photo";
import { usePhase } from "./PhaseProvider";
import { liveOwner, demoDate } from "@/lib/phase-demo";
import { getDemo } from "@/lib/demo";
export function LocalGuideDemo({ initialZone, now = false }: { initialZone?: string; now?: boolean }) {
  const { has } = usePhase(); const matching=now&&has("onDemandGuides");
  const [destination,setDestination] = useState(initialZone ? guideProfiles.find((guide) => guide.zone === initialZone || guide.destination === initialZone)?.destination || "" : ""); const [interest,setInterest] = useState("");
  const guides = guideProfiles.filter((guide) => (!matching || liveOwner(guide.id === "nadeesha-perera" ? "guide-demo" : `guide-${guide.id}`)) && (!destination || guide.destination === destination) && (!interest || guide.specialties.some((specialty) => specialty.toLowerCase().includes(interest))));
  return <div className="guide-list-page"><div className="content-width"><div className="guide-intro"><div><h1>{matching?"Travel Buddy Now":"A place feels different when you know a local."}</h1><p>Discover the stories, small streets, and favorite stops you might otherwise walk past. Find a local perspective for your kind of day.</p><span className="demo-badge">Guide session demo · Sample profiles</span></div><Photo src={experiences[0].gallery[1]} alt="Colombo, Sri Lanka" /></div><div className="guide-search-controls"><div className="field"><label htmlFor="guide-city">Where are you exploring?</label><select id="guide-city" value={destination} onChange={(e) => setDestination(e.target.value)}><option value="">Anywhere in Sri Lanka</option>{Array.from(new Set(guideProfiles.map((guide) => guide.destination))).map((city) => <option key={city}>{city}</option>)}</select></div><div className="field"><label htmlFor="guide-interest">What interests you?</label><select id="guide-interest" value={interest} onChange={(e) => setInterest(e.target.value)}><option value="">A little of everything</option><option value="food">Food & flavors</option><option value="history">History</option><option value="culture">Culture</option><option value="hike">Hikes & viewpoints</option><option value="tea">Tea country</option></select></div></div><div className="section-heading"><div><h2>{destination ? `Get to know ${destination}.` : "Meet your local perspective."}</h2><p>{guides.length} sample {guides.length === 1 ? "profile" : "profiles"} · Availability and guide dispatch are not connected.</p></div></div>{guides.length ? <div className="guide-grid">{guides.map((guide) => <GuideProfileCard key={guide.id} guide={guide} now={matching} />)}</div> : <div className="empty-state"><MapPin size={30} /><h2>Try another interest or place.</h2><p>There isn’t a sample guide for this combination yet.</p><button className="button button-secondary" onClick={() => {setDestination("");setInterest("");}}>Show all guides</button></div>}<p className="inline-note">Profiles, photographs, and reviews are illustrative. Exploring this demo will not contact or book a real guide.</p></div></div>;
}
