"use client";
import Link from "next/link";
import { ArrowRight, CalendarDays, Plus, QrCode, Heart, MapPin } from "lucide-react";
import { useEffect, useState } from "react";
import { createJourneyPlan, readJourneyPlans, writeJourneyPlans, type JourneyPlan, getExperienceForJourneyEvent } from "@/lib/journey";
import { readBookings, type Booking } from "@/lib/traveler";
import { Photo } from "./Photo";
import { experiences } from "@/lib/catalog";

import { usePhase, FeatureGate } from "./PhaseProvider";
import { BookingHistory } from "./PhaseWorkflows";
export function MyTrips() {
  const [plans, setPlans] = useState<JourneyPlan[]>([]); const [bookings, setBookings] = useState<Booking[]>([]); const [tab, setTab] = useState("plans"); const [creating, setCreating] = useState(false); const [name, setName] = useState("");
  useEffect(() => { setPlans(readJourneyPlans()); setBookings(readBookings()); if (new URLSearchParams(window.location.search).get("view") === "bookings") setTab("bookings"); }, []);
  function create(e: React.FormEvent) { e.preventDefault(); const plan = createJourneyPlan(name.trim()); writeJourneyPlans([plan, ...readJourneyPlans()]); window.location.href = `/trips/${plan.id}`; }
  return <div className="workspace-page"><div className="content-width"><div className="page-heading"><div><h1>Your journeys, together.</h1><p>From the first idea to the day you go.</p></div><button className="button button-primary" onClick={() => setCreating(!creating)}><Plus size={17} /> Create a trip</button></div><div className="workspace-topline"><div className="segment-tabs" role="tablist" aria-label="Travel workspace"><button role="tab" aria-selected={tab === "plans"} className={tab === "plans" ? "active" : ""} onClick={() => setTab("plans")}>Plans <span>{plans.length}</span></button><button role="tab" aria-selected={tab === "bookings"} className={tab === "bookings" ? "active" : ""} onClick={() => setTab("bookings")}>Bookings <span>{bookings.length}</span></button></div><div className="workspace-links"><Link href="/saved"><Heart size={16} /> Saved</Link><FeatureGate feature="offlineQr"><Link href="/scan"><QrCode size={16} /> Import trip</Link></FeatureGate></div></div>{creating && <form className="create-trip-form" onSubmit={create}><div className="field"><label htmlFor="trip-name">Give your trip a name</label><input id="trip-name" placeholder="e.g. A week in Sri Lanka" value={name} onChange={(e) => setName(e.target.value)} maxLength={60} required autoFocus /></div><button className="button button-primary" type="submit">Start planning <ArrowRight size={16} /></button><button className="text-link" type="button" onClick={() => setCreating(false)}>Cancel</button></form>}{tab === "plans" ? <><div className="trip-grid">{plans.map((plan) => { const cover = (plan.events[0] ? getExperienceForJourneyEvent(plan.events[0]) : undefined) || experiences[1]; return <Link href={`/trips/${plan.id}`} className="trip-card" key={plan.id}><div className="trip-cover"><Photo src={cover.image} alt={cover.destination} />{plan.id.startsWith("journey-sri-lanka") && <span className="demo-badge">Sample plan</span>}<span className="trip-cover-days"><CalendarDays size={15} /> {plan.days} {plan.days === 1 ? "day" : "days"}</span></div><div className="trip-card-body"><span className="card-location"><MapPin size={13} /> {Array.from(new Set(plan.events.map((event) => getExperienceForJourneyEvent(event)?.destination).filter(Boolean))).join(" · ") || "Your next destination"}</span><h2>{plan.name}</h2><div><span>{plan.startDate||"Choose travel dates"} · {plan.events.length} activities · {plan.events.filter(e=>e.status==="completed").length}/{plan.events.length} complete</span><ArrowUpRightIcon /></div></div></Link>; })}<button className="new-trip-card" onClick={() => setCreating(true)}><span><Plus size={25} /></span><h2>Where to next?</h2><p>Turn a few good ideas into a trip.</p><strong>Create a new plan</strong></button></div><p className="inline-note">Plans stay in this browser.</p></> : <BookingHistory embedded />}</div></div>;
}
function ArrowUpRightIcon() { return <ArrowRight size={20} />; }
