"use client";
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { Check, MessageCircle } from 'lucide-react';
import { getDemo, getSession, saveDemo } from '@/lib/demo';
import { conversations, liveOwner, setLive, requests, reviews } from '@/lib/phase-demo';
import { readBookings, readLocal, writeLocal, type Booking } from '@/lib/traveler';
import { readJourneyPlans, type JourneyPlan } from '@/lib/journey';

export function RecentConversations({ owner }: { owner: string }) {
  const rows=conversations().filter(c=>c.peer===owner);
  return <div>{rows.length?rows.slice(0,3).map(c=><Link className="compact-record" key={c.id} href="/supplier/inbox"><strong>{getDemo().accounts.find(a=>a.id===c.traveler)?.name||'Demo traveler'}</strong><span>{c.messages.at(-1)?.text}</span></Link>):<p>No inquiries yet. Contact this provider from an experience to try the conversation flow.</p>}</div>;
}
export function SubmittedReviews({ owner }: { owner: string }) {
  const data=getDemo();const listingIds=data.listings.filter(l=>l.owner===owner).map(l=>l.id);const rows=reviews().filter(r=>listingIds.includes(r.experience));
  return <section className="management-panel"><h2>Locally submitted reviews</h2>{rows.length?rows.map(r=><article key={r.id}><strong>{data.listings.find(l=>l.id===r.experience)?.title} · {r.rating} / 5</strong><p>{r.text}</p><small>Demonstration feedback · {data.accounts.find(a=>a.id===r.owner)?.name||'Demo traveler'}</small></article>):<p>No locally submitted reviews yet.</p>}</section>;
}

export function LiveToggle({ owner }: { owner: string }) {
  const [live,update]=useState(false);
  useEffect(()=>update(liveOwner(owner)),[owner]);
  return <div className="live-toggle"><div><strong>{live?'Accepting Live Now requests':'Currently offline'}</strong><p>Updates provider visibility in the local demo marketplace.</p></div><button className={`button ${live?'button-secondary':'button-primary'}`} aria-pressed={live} onClick={()=>{setLive(owner,!live);update(!live);}}>{live?'Go Offline':'Go Live'}</button></div>;
}

export function SessionQuestions({ guideId }: { guideId: string }) {
  const [question,setQuestion]=useState('');const [messages,setMessages]=useState<{question:string;answer:string}[]>([]);
  useEffect(()=>setMessages(readLocal(`tb-session-questions:${guideId}`,[])),[guideId]);
  return <section className="session-questions"><h3>Questions for your demo guide</h3><p>Answers are scripted locally. No guide is participating.</p><div role="log">{messages.map((m,i)=><div key={i}><strong>{m.question}</strong><p>{m.answer}</p></div>)}</div><form onSubmit={e=>{e.preventDefault();const answer=/food|eat/i.test(question)?'Sample answer: try a small local café near the fort and ask about the daily specials.':/meet|where/i.test(question)?'Sample answer: use the meeting area in your session summary. This demo does not track your location.':'Sample answer: take time to explore the shaded streets and historic courtyards. Your guide can adapt the route to your interests.';const next=[...messages,{question:question.trim(),answer}];setMessages(next);writeLocal(`tb-session-questions:${guideId}`,next);setQuestion('');}}><label className="field">Your question<input required maxLength={300} value={question} onChange={e=>setQuestion(e.target.value)}/></label><button className="button button-secondary" disabled={!question.trim()}><MessageCircle size={16}/>Ask demo guide</button></form></section>;
}

export function Collaboration() {
  const [accepted,setAccepted]=useState<string[]>([]);
  useEffect(()=>setAccepted(readLocal(`tb-collaborations:${getSession()?.id}`,[])),[]);
  return <div><div className="page-heading"><div><h1>Local collaboration</h1><p>Shared packages and sample partnership opportunities.</p></div></div>{['Galle heritage walk + Colombo food experience','Sigiriya discovery + local transport'].map(title=><section className="management-panel" key={title}><span className="demo-badge">Sample proposal</span><h2>{title}</h2><p>Preview a local partnership. No business is contacted and no agreement is created.</p><button className="button button-secondary" disabled={accepted.includes(title)} onClick={()=>{const next=[...accepted,title];setAccepted(next);writeLocal(`tb-collaborations:${getSession()?.id}`,next);}}>{accepted.includes(title)?'Interest saved locally':'Save collaboration interest'}</button></section>)}</div>;
}

export function AdminPhaseTools({ section }: { section: string }) {
  const [query,setQuery]=useState('');const [hidden,setHidden]=useState<string[]>([]);const [revision,setRevision]=useState(0);const [notice,setNotice]=useState('');
  useEffect(()=>setHidden(readLocal('tb-moderation-hidden',[])),[]);
  const data=getDemo();
  const entries=section==='community'?requests().map(r=>({id:r.id,title:r.destination,detail:`${r.visibility} · ${r.message}`})):section==='reviews'?reviews().map(r=>({id:r.id,title:data.listings.find(l=>l.id===r.experience)?.title||r.experience,detail:`${r.rating} / 5 · ${r.text}`})):section==='sessions'?data.sessions.map(s=>({id:s.id,title:`${s.category} · ${s.traveler}`,detail:`${s.date} · ${s.zone} · ${s.status}`})):section==='journeys'?data.bookings.filter(b=>(b.experienceIds?.length||0)>1||b.journeySummary).map(b=>({id:b.id,title:data.listings.find(l=>l.id===b.experienceId)?.title||b.id,detail:b.journeySummary||`${b.experienceIds?.length} experiences · ${b.amount}`})):[{id:'partner-1',title:'Ceylon Compass × Local perspectives',detail:'Sample shared package · Illustrative referrals: 12'}];
  return <div><div className="page-heading"><div><h1>{section==='journeys'?'Connected journeys':section==='sessions'?'Simulated guide sessions':section==='partnerships'?'Partnerships':section==='reviews'?'Review moderation':'Community content'}</h1><p>Local oversight demonstration. No production service or enforcement.</p></div></div><label className="field">Search records<input type="search" value={query} onChange={e=>setQuery(e.target.value)}/></label>{entries.filter(e=>`${e.title} ${e.detail}`.toLowerCase().includes(query.toLowerCase())).map(e=><article className="management-panel" key={e.id}><h2>{e.title}</h2><p>{e.detail}</p><button className="text-link" onClick={()=>{const next=hidden.includes(e.id)?hidden.filter(id=>id!==e.id):[...hidden,e.id];setHidden(next);writeLocal('tb-moderation-hidden',next);setNotice('Local moderation state updated.');}}>{hidden.includes(e.id)?'Clear local review flag':'Flag for local review'}</button></article>)}{!entries.length&&<div className="empty-state"><h2>No {section} records yet.</h2><p>Complete the relevant traveler workflow to create demonstration records.</p></div>}{notice&&<p role="status">{notice}</p>}</div>;
}

type HistoryBundle = { version: 1; bookings: Booking[]; trips: JourneyPlan[] };
export function PortableHistory() {
  const [bundle,setBundle]=useState<HistoryBundle>({version:1,bookings:[],trips:[]});const [text,setText]=useState('');const [preview,setPreview]=useState<HistoryBundle|null>(null);const [notice,setNotice]=useState('');
  useEffect(()=>setBundle({version:1,bookings:readBookings().filter(b=>b.status==='Completed'),trips:readJourneyPlans().filter(p=>p.events.length>0&&p.events.every(e=>e.status==='completed'))}),[]);
  function validate(){try{if(text.length>150000)throw Error();const value=JSON.parse(text);if(value.version!==1||!Array.isArray(value.bookings)||!Array.isArray(value.trips)||value.bookings.length>100||value.trips.length>100)throw Error();if(!value.bookings.every((b:Booking)=>typeof b.title==='string'&&typeof b.date==='string'&&typeof b.id==='string'&&typeof b.total==='number'&&Number.isFinite(b.total)&&typeof b.image==='string'&&Array.isArray(b.experienceIds)&&b.experienceIds.every(id=>typeof id==='string'))||!value.trips.every((p:JourneyPlan)=>typeof p.name==='string'&&typeof p.id==='string'&&Number.isInteger(p.days)&&Array.isArray(p.events)&&p.events.every(e=>typeof e.id==='string'&&Number.isInteger(e.day))))throw Error();setPreview(value);setNotice('Valid local history copy. Review before importing.');}catch{setPreview(null);setNotice('This is not a valid TravelBuddy history export. Paste an exported JSON bundle.');}}
  return <div className="workspace-page content-width"><div className="page-heading"><div><h1>Your travel history</h1><p>This demonstration previews a local history copy on another device. Real synchronization is not enabled.</p></div><button className="button button-secondary" onClick={()=>{const safe={version:1,bookings:bundle.bookings.map(b=>({id:b.id,title:b.title,image:b.image,experienceIds:b.experienceIds,date:b.date,time:b.time,travelers:b.travelers,total:b.total,payLater:b.payLater,meetingPoint:b.meetingPoint,createdAt:b.createdAt,status:b.status})),trips:bundle.trips};setText(JSON.stringify(safe,null,2));setNotice('Export ready below. Copy it to carry a local history preview.');}}>Export history</button></div><h2>Completed experiences</h2>{bundle.bookings.map(b=><article className="management-panel" key={b.id}><h3>{b.title}</h3><p>{b.date} · {b.travelers} travelers</p><Link className="text-link" href={`/booking/${b.id}`}>View booking</Link></article>)}{!bundle.bookings.length&&<p>No completed experiences yet.</p>}<h2>Imported device preview</h2>{readLocal<HistoryBundle|null>("tb-portable-history",null)?.bookings.map(b=><p key={b.id}>{b.title} · {b.date} · Imported copy</p>)}<h2>Past trips</h2>{bundle.trips.map(p=><p key={p.id}>{p.name} · {p.days} days</p>)}{!bundle.trips.length&&<p>No completed trips yet.</p>}<section className="management-panel"><h2>Portable history preview</h2><label className="field">Exported history JSON<textarea rows={7} value={text} onChange={e=>{setText(e.target.value);setPreview(null);}} maxLength={150000}/></label><button className="button button-secondary" disabled={!text.trim()} onClick={validate}>Review import</button>{preview&&<div><h3>Review this device copy</h3><p>{preview.bookings.length} completed experiences · {preview.trips.length} trips</p>{preview.bookings.map(b=><p key={b.id}>{b.title} · {b.date}</p>)}<button className="button button-primary" onClick={()=>{writeLocal('tb-portable-history',preview);setNotice('History preview saved locally. Your bookings and account are unchanged.');setPreview(null);}}>Save imported preview</button></div>}{notice&&<p role="status">{notice}</p>}</section></div>;
}
