"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { ArrowLeft, CalendarDays, ChevronRight, CircleHelp, ClipboardList, Globe2, LayoutDashboard, Package, ShieldCheck, Users, UserRound } from "lucide-react";
import { useState, type ReactNode } from "react";
import { StatCard } from "./ExperienceCard";
import { Brand } from "./AppShell";
type PortalNav = {label:string;icon:ReactNode;href?:string}[];
export function PortalLayout({role,title,subtitle,children,nav}:{role:string;title:string;subtitle:string;children:ReactNode;nav:PortalNav}) {
  const pathname = usePathname();const [notice,setNotice] = useState("");
  const active = (href:string) => pathname === href || href !== nav[0]?.href && pathname.startsWith(`${href}/`);
  const mobile = nav.filter((item) => item.href && item.href !== "#").slice(0,3);
  return <div className="portal-wrap"><aside className="portal-sidebar"><Brand /><div className="portal-label">{role} · Demo workspace</div><nav className="portal-nav" aria-label={`${role} navigation`}>{nav.map((item) => item.href && item.href !== "#" ? <Link key={item.label} href={item.href} className={active(item.href) ? "selected" : ""} aria-current={active(item.href) ? "page" : undefined}>{item.icon}<span>{item.label}</span></Link> : <button key={item.label} disabled title="Unavailable in this prototype">{item.icon}<span>{item.label}</span></button>)}</nav><Link className="sidebar-help" href="/support"><CircleHelp size={20} /><div><strong>About this prototype</strong><span>Get help with demo features</span></div></Link><Link className="portal-back" href="/"><ArrowLeft size={15} /> Back to Explore</Link></aside><section className="portal-content" onClick={(e) => { const target = e.target as HTMLElement; const link = target.closest("a"); if (link?.getAttribute("href") === "#") {e.preventDefault();setNotice("This action is a preview of a future workspace feature. It is not connected in this demo.");} }}><div className="portal-mobile-head"><Brand /><span>{role}</span></div><nav className="portal-mobile-nav" aria-label={`${role} navigation`}>{mobile.map((item) => <Link key={item.label} href={item.href!} className={active(item.href!) ? "selected" : ""}>{item.icon}<span>{item.label}</span></Link>)}<Link href="/login"><UserRound size={18} /><span>Workspaces</span></Link></nav><div className="portal-demo-notice"><ShieldCheck size={16} /> Demo workspace. Metrics and records are illustrative; unavailable actions are labeled or disabled.</div><div className="portal-heading"><div><div className="breadcrumb">TravelBuddy / {role}</div><h1>{title}</h1><p>{subtitle}</p></div><Link href="/support" className="button button-secondary"><CircleHelp size={16} /> Help</Link></div>{notice && <div className="notice" role="status" style={{marginBottom:25}}><span>{notice}</span><button className="text-link" onClick={() => setNotice("")}>Dismiss</button></div>}{children}</section></div>;
}
export const supplierNav:PortalNav = [{label:"Overview",icon:<LayoutDashboard size={18} />,href:"/supplier"},{label:"Experiences",icon:<Package size={18} />,href:"/supplier/products"},{label:"Bookings",icon:<ClipboardList size={18} />,href:"/supplier/bookings"},{label:"Availability",icon:<CalendarDays size={18} />,href:"#"}];
export const advisorNav:PortalNav = [{label:"Overview",icon:<LayoutDashboard size={18} />,href:"/advisor"},{label:"Client trips",icon:<Users size={18} />,href:"#"},{label:"Client bookings",icon:<ClipboardList size={18} />,href:"#"},{label:"Find experiences",icon:<Globe2 size={18} />,href:"/search"}];
export const partnerNav:PortalNav = [{label:"Overview",icon:<LayoutDashboard size={18} />,href:"/partner"},{label:"Referral tools",icon:<Globe2 size={18} />,href:"#"},{label:"Performance",icon:<ClipboardList size={18} />,href:"#"}];
export const adminNav:PortalNav = [{label:"Overview",icon:<LayoutDashboard size={18} />,href:"/admin"},{label:"Content",icon:<Package size={18} />,href:"#"},{label:"Booking oversight",icon:<ClipboardList size={18} />,href:"#"},{label:"Suppliers",icon:<Users size={18} />,href:"#"}];
export function DashboardTable({rows}:{rows:{id:string;title:string;meta:string;status:string;amount:string}[]}) {return <div className="data-table"><div className="table-head"><span>Reference / experience</span><span>Status</span><span>Value</span><span /></div>{rows.map((row) => <div className="table-row" key={row.id}><div><strong>{row.id}</strong><span>{row.title}</span><small>{row.meta}</small></div><span className={`status status-${row.status.toLowerCase().replaceAll(" ","-")}`}>{row.status}</span><strong>{row.amount}</strong><ChevronRight size={17} /></div>)}</div>;}
export function PortalStats({stats}:{stats:{label:string;value:string;detail:string;tone?:string}[]}) {return <div className="stats-grid">{stats.map((stat) => <StatCard key={stat.label} {...stat} />)}</div>;}
