"use client";
import Link from "next/link";
import { CalendarDays, ChevronRight, CircleHelp, Globe2, Heart, Laptop, Moon, ShieldCheck, Sun, UserRound } from "lucide-react";
import { useEffect, useState } from "react";
import { readLocal, writeLocal } from "@/lib/traveler";
export default function AccountPage() {
  const [name,setName] = useState("Traveler"); const [theme,setTheme] = useState("light"); const [updates,setUpdates] = useState(false);
  useEffect(() => {const profile = readLocal<{name:string}>("tb-demo-profile",{name:"Traveler"});setName(profile.name);setTheme(readLocal<string>("tb-theme","light"));setUpdates(readLocal<boolean>("tb-email-preference",false));},[]);
  function changeTheme(value:string) {setTheme(value);writeLocal("tb-theme",value);document.documentElement.dataset.theme = value;}
  const links = [{title:"My trips",detail:"Plans, itineraries, and demo bookings",href:"/trips",icon:CalendarDays},{title:"Saved experiences",detail:"The places that caught your eye",href:"/saved",icon:Heart},{title:"Help & support",detail:"How the prototype works",href:"/support",icon:CircleHelp}];
  return <div className="profile-page"><div className="content-width"><div className="page-heading"><div><h1>A little more you.</h1><p>Your travel space, just the way you like it.</p></div></div><div className="profile-layout"><aside className="profile-identity"><div className="profile-avatar"><UserRound size={29} /></div><h2>Hello, {name.split(" ")[0]}.</h2><p>You’re exploring the traveler prototype. Your plans and preferences stay on this device.</p><span className="demo-badge">Local demo profile</span><Link className="button button-secondary button-wide" style={{marginTop:25}} href="/login/standard">Set up demo profile</Link></aside><div><section className="settings-section"><h2>Your travel essentials</h2>{links.map(({icon:Icon,...link}) => <Link href={link.href} className="settings-row" key={link.title}><Icon size={21} /><div><strong>{link.title}</strong><small>{link.detail}</small></div><ChevronRight size={19} /></Link>)}</section><section className="settings-section"><h2>Make yourself at home</h2><div className="settings-row"><Globe2 size={21} /><div><strong>Language & currency</strong><small>English · USD. This sample catalog uses US dollars.</small></div></div><div className="settings-row">{theme === "dark" ? <Moon size={21} /> : <Sun size={21} />}<div><label htmlFor="appearance"><strong>Appearance</strong></label><small>A comfortable view for wherever you are.</small></div><select id="appearance" value={theme} onChange={(e) => changeTheme(e.target.value)}><option value="light">Light</option><option value="dark">Dark</option></select></div><label className="settings-row"><Heart size={21} /><div><strong>Travel inspiration</strong><small>Save an email preference locally. No emails are sent.</small></div><input type="checkbox" checked={updates} onChange={(e) => {setUpdates(e.target.checked);writeLocal("tb-email-preference",e.target.checked);}} /></label></section><section className="settings-section"><h2>About your workspace</h2><div className="settings-row"><ShieldCheck size={21} /><div><strong>Saved on this device</strong><small>Trips, saved ideas, and demo bookings do not sync between devices. Use a trip QR to share a copy.</small></div></div><Link href="/login" className="settings-row"><Laptop size={21} /><div><strong>Explore business workspaces</strong><small>Supplier, advisor, partner, and admin demos.</small></div><ChevronRight size={19} /></Link></section></div></div></div></div>;
}
